### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by IliaIlin** [SH-Files/First-Project#5]
https://github.com/SH-Files/First-Project/blob/f95bc05c308a5d9ecd2c8a0d1ae4327f68f200e0/src/Main.java#L86

No need to reinvent the wheel, here I see how complex your code has become. With the same effect, you could have used ArrayList

**Comment by SH-Files** [comment]
I closed this because I feel like this is just a tip for the future. Tell me if I am wrong. I will rewrite it then.

I used TreeMap because it did make it easier for me to get a certain course removed from a student because I could just search for the corresponding key. 

If I would have used ArrayLists an additional attribute (ID) for both classes (Student, Course) would have been necessary. I think the implementation would be a bit more difficult compared to using TreeMap.

Guess I was wrong.
